import type { EventRow } from "@/types/db";

// `EventRow` is auto-generated by `npm run supabase:types`. Until that
// regen is run after migrations 0016/0017, the codegen has no record of
// the columns we just added. This local augmentation lets the module
// typecheck on a fresh clone; regenerating db.ts later is a no-op for
// behavior since these fields will exist in the generated type.
export type EventRowWithOrganizer = EventRow & {
  organizer_user_id: string | null;
  organizer_resale_royalty_bps: number;
};
