// Hand-written DB types (generated by `pnpm supabase:types` in real workflow).
// Keep in sync with supabase/migrations/0001_init.sql.

export type UserRole = "user" | "controller" | "admin";
export type WalletType = "custodial" | "external";
export type EventStatus = "draft" | "published" | "canceled" | "completed";
export type Currency = "MAD" | "EUR";
export type TicketStatus =
  | "available"
  | "reserved"
  | "sold"
  | "listed"
  | "used"
  | "expired"
  | "refund_pending"
  | "refunded"
  | "canceled";
export type PurchaseStatus = "pending" | "paid" | "failed" | "refunded";
export type ListingStatus = "active" | "sold" | "canceled" | "expired";
export type RedemptionResult =
  | "valid"
  | "already_used"
  | "refunded"
  | "canceled"
  | "wrong_event"
  | "expired"
  | "owner_mismatch"
  | "invalid_signature"
  | "tx_failed"
  | "tx_pending"
  | "no_ticket"
  | "no_session";

export type GateSessionStatus = "open" | "closed" | "expired";

export interface Profile {
  id: string;
  email: string;
  display_name: string | null;
  role: UserRole;
  pro_crypto_mode: boolean;
  created_at: string;
}

export interface Wallet {
  id: string;
  user_id: string;
  wallet_address: string;
  encrypted_secret_key: string | null;
  wallet_type: WalletType;
  is_primary: boolean;
  created_at: string;
}

export interface EventRow {
  id: string;
  name: string;
  date: string;
  venue_name: string;
  city: string;
  capacity: number;
  image_url: string | null;
  description: string | null;
  conditions: string | null;
  sales_enabled: boolean;
  resale_enabled: boolean;
  public_sales_counter_enabled: boolean;
  status: EventStatus;
  solana_collection_address: string | null;
  created_at: string;
  updated_at: string;
}

export interface TicketCategory {
  id: string;
  event_id: string;
  name: string;
  description: string | null;
  price: string; // numeric returned as string
  currency: Currency;
  supply: number;
  sold_count: number;
  max_resale_price: string | null;
  resale_enabled: boolean;
  benefits: string | null;
  created_at: string;
}

export interface Ticket {
  id: string;
  event_id: string;
  category_id: string;
  serial_number: number;
  owner_user_id: string | null;
  owner_wallet_address: string | null;
  nft_asset_address: string | null;
  metadata_uri: string | null;
  image_url: string | null;
  status: TicketStatus;
  reserved_until: string | null;
  original_purchase_id: string | null;
  current_listing_id: string | null;
  minted_at: string | null;
  used_at: string | null;
  refunded_at: string | null;
  canceled_at: string | null;
  redeem_tx_signature: string | null;
  redemption_pda: string | null;
  redeemed_wallet_address: string | null;
  created_at: string;
  updated_at: string;
}

export interface Purchase {
  id: string;
  buyer_user_id: string;
  event_id: string;
  ticket_id: string;
  provider_session_id: string | null;
  provider_payment_id: string | null;
  payment_provider: string | null;
  amount: string;
  currency: Currency;
  status: PurchaseStatus;
  created_at: string;
  paid_at: string | null;
}

export interface ResaleListing {
  id: string;
  ticket_id: string;
  seller_user_id: string;
  buyer_user_id: string | null;
  price: string;
  currency: Currency;
  status: ListingStatus;
  provider_session_id: string | null;
  payment_provider: string | null;
  created_at: string;
  sold_at: string | null;
}

export interface TicketRedemption {
  id: string;
  ticket_id: string;
  event_id: string;
  controller_user_id: string;
  wallet_address: string;
  signature: string | null;
  redeemed_at: string;
  gate_name: string | null;
  result: RedemptionResult;
  gate_session_id: string | null;
  redeem_tx_signature: string | null;
  redemption_pda: string | null;
}

export interface GateSession {
  id: string;
  event_id: string;
  controller_user_id: string;
  gate_name: string | null;
  short_code: string;
  status: GateSessionStatus;
  expires_at: string;
  opened_at: string;
  closed_at: string | null;
  last_redemption_id: string | null;
  last_result: string | null;
  last_ticket_id: string | null;
  created_at: string;
}

export interface AuditLog {
  id: string;
  actor_user_id: string | null;
  action: string;
  entity_type: string;
  entity_id: string;
  metadata_json: Record<string, unknown> | null;
  created_at: string;
}
