// scripts/compile-contracts.ts
//
// Compiles `contracts/MisoTicket.sol` using solc-js + OpenZeppelin sources
// resolved from node_modules. Writes the resulting bytecode hex string to
// `src/lib/thirdweb/contracts/misoTicket.bytecode.ts` and a full artifact
// (abi + bytecode + metadata) to `artifacts/MisoTicket.json` for reference.
//
// Run with: npm run contracts:compile
//
// Deterministic: optimizer enabled, runs=200, evmVersion=paris. Re-running
// against unchanged sources produces an identical bytecode file.

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

import solc from "solc";

interface SolcInputSource {
  content: string;
}

interface SolcInput {
  language: "Solidity";
  sources: Record<string, SolcInputSource>;
  settings: {
    optimizer: { enabled: boolean; runs: number };
    evmVersion: string;
    outputSelection: Record<string, Record<string, string[]>>;
  };
}

interface SolcOutput {
  errors?: Array<{ severity: string; formattedMessage: string }>;
  contracts: Record<
    string,
    Record<
      string,
      {
        abi: unknown[];
        evm: { bytecode: { object: string } };
      }
    >
  >;
}

const ROOT = resolve(__dirname, "..");
const ENTRY = "contracts/MisoTicket.sol";
const CONTRACT_NAME = "MisoTicket";
const ARTIFACTS_DIR = join(ROOT, "artifacts");
const ARTIFACT_PATH = join(ARTIFACTS_DIR, `${CONTRACT_NAME}.json`);
const BYTECODE_OUT = join(
  ROOT,
  "src/lib/thirdweb/contracts/misoTicket.bytecode.ts",
);

function resolveImport(importPath: string): { contents: string } | { error: string } {
  try {
    if (importPath.startsWith("@openzeppelin/")) {
      const full = require.resolve(importPath, { paths: [ROOT] });
      return { contents: readFileSync(full, "utf8") };
    }
    const full = join(ROOT, importPath);
    return { contents: readFileSync(full, "utf8") };
  } catch (err) {
    return { error: `Cannot resolve ${importPath}: ${(err as Error).message}` };
  }
}

function buildInput(): SolcInput {
  return {
    language: "Solidity",
    sources: {
      [ENTRY]: { content: readFileSync(join(ROOT, ENTRY), "utf8") },
    },
    settings: {
      optimizer: { enabled: true, runs: 200 },
      evmVersion: "cancun",
      outputSelection: {
        "*": {
          "*": ["abi", "evm.bytecode.object"],
        },
      },
    },
  };
}

function compile(): SolcOutput {
  const input = JSON.stringify(buildInput());
  const raw = solc.compile(input, { import: resolveImport });
  return JSON.parse(raw) as SolcOutput;
}

function writeBytecodeFile(bytecode: string) {
  const content = `// AUTO-GENERATED by scripts/compile-contracts.ts. Do not edit by hand.
// Source: contracts/MisoTicket.sol
// Re-run \`npm run contracts:compile\` after editing the Solidity source.

import type { Hex } from "viem";

export const MISO_TICKET_BYTECODE = "0x${bytecode}" as Hex;
`;
  mkdirSync(dirname(BYTECODE_OUT), { recursive: true });
  writeFileSync(BYTECODE_OUT, content);
}

function writeArtifact(abi: unknown[], bytecode: string) {
  mkdirSync(ARTIFACTS_DIR, { recursive: true });
  writeFileSync(
    ARTIFACT_PATH,
    JSON.stringify(
      { contractName: CONTRACT_NAME, abi, bytecode: `0x${bytecode}` },
      null,
      2,
    ),
  );
}

function main() {
  const output = compile();

  const fatal = (output.errors ?? []).filter((e) => e.severity === "error");
  if (fatal.length > 0) {
    for (const err of fatal) console.error(err.formattedMessage);
    throw new Error(`Solidity compile failed with ${fatal.length} error(s)`);
  }
  for (const warn of output.errors ?? []) {
    if (warn.severity !== "error") console.warn(warn.formattedMessage);
  }

  const compiled = output.contracts[ENTRY]?.[CONTRACT_NAME];
  if (!compiled) {
    throw new Error(`Compiled output missing ${CONTRACT_NAME}`);
  }
  const bytecode = compiled.evm.bytecode.object;
  if (!bytecode || bytecode.length === 0) {
    throw new Error("Compiled bytecode is empty");
  }

  writeBytecodeFile(bytecode);
  writeArtifact(compiled.abi, bytecode);
  console.log(`Wrote ${BYTECODE_OUT} (${bytecode.length / 2} bytes)`);
  console.log(`Wrote ${ARTIFACT_PATH}`);
}

main();
